### PR TITLE
panel.margin -> panel.spacing

### PR DESCRIPTION
**Pull request by vladpetyuk**
an easy fix to the issue of compatibility with a new ggplot2 version

### CODE REVIEW

**Comment by assaron** [comment]
Hi, for which ggplot2 version exactly panel.margin didn't work? I have 2.1.0 and it seems to work fine (but not with panel.spacing). I found a thread on the stackoverflow that it's deprecated (http://stackoverflow.com/a/3682851) but no sign of panel.spacing in the recent theme documentation: http://docs.ggplot2.org/current/theme.html

**Comment by vladpetyuk** [comment]
I have already re-installed R and the packages. So I got 2.1.0 back and it
is working just fine with `plotGseaTable`.  It looks like I transiently had
version 2.2.0.  There are quite a few changes coming in 2-3 weeks.
https://blog.rstudio.org/2016/09/30/ggplot2-2-2-0-coming-soon/
I guess you can ignore the issue for now until the 2.2.0 is out.

**Comment by assaron** [comment]
I see, it seems I'll need to implement a hack that will check the ggplot version at some point.

**Comment by vladpetyuk** [comment]
I'd just put ggplot2(>=2.2.0) into the Imports field of the DESCRIPTION
file for the next release.  Hopefully the users will catch up with ggplot2
version soon after its release.

**Comment by GuangchuangYu** [comment]
`ggtree` supports both versions (2.1.0 & 2.2.0) of `ggplot2`, through something like this <https://github.com/GuangchuangYu/ggtree/blob/master/R/geom_hilight.R#L43>.

**Comment by vladpetyuk** [comment]
Gosh! I hope this is a rare exception rather then a norm :)  Nice workaround though.

**Comment by GuangchuangYu** [comment]
I will put `ggplot2(>=2.2.0)` in `Dependes` and remove the `if` test in `ggtree` devel branch when `ggplot2 v2.2.0` is available.

The solution is just to keep the `release` branch untouched :).

**Comment by assaron** [comment]
fgsea is now compatible with ggplot 2.2

**Pull request closed without merging**
